sonata_admin:
    # title: 'The Ineluctable'
    title_logo: images/logo-01.png
    templates:
      edit: 'Admin/edit.html.twig'
      dashboard: 'Admin/dashboard.html.twig'
    assets:
      extra_stylesheets: ['build/js/skins/lightgray/skin.min.css', 'build/js/skins/lightgray/content.min.css', 'build/css/admin.css', 'build/css/admin-menu.css', 'build/css/app.css']
      extra_javascripts: ['build/manifest.js', 'build/vendor.js', 'build/js/jquery-tinymce.js', 'build/js/tinymce.js', 'build/js/themes/modern/theme.js', 'build/js/plugins/image/plugin.js', 'build/js/plugins/lists/plugin.js', 'build/js/plugins/textcolor/plugin.js', 'build/js/plugins/link/plugin.js', 'build/js/app.js']
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
